// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEqrTQ3OOo18qEAazJS7hVyUzb34L4Dio',
    appId: '1:1059073654273:web:15b8b08968118c90d64a00',
    messagingSenderId: '1059073654273',
    projectId: 'novelai-61453',
    authDomain: 'novelai-61453.firebaseapp.com',
    storageBucket: 'novelai-61453.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy9hr3aIRhNN6QVNXTrQHCg6QBlGOzBx4',
    appId: '1:1059073654273:android:7d32bc6768d33fefd64a00',
    messagingSenderId: '1059073654273',
    projectId: 'novelai-61453',
    storageBucket: 'novelai-61453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9WyevawK8c5EuXFWqfMPN9AuQhzStX90',
    appId: '1:1059073654273:ios:51ab8563b964f97bd64a00',
    messagingSenderId: '1059073654273',
    projectId: 'novelai-61453',
    storageBucket: 'novelai-61453.firebasestorage.app',
    iosBundleId: 'com.example.accproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9WyevawK8c5EuXFWqfMPN9AuQhzStX90',
    appId: '1:1059073654273:ios:51ab8563b964f97bd64a00',
    messagingSenderId: '1059073654273',
    projectId: 'novelai-61453',
    storageBucket: 'novelai-61453.firebasestorage.app',
    iosBundleId: 'com.example.accproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEqrTQ3OOo18qEAazJS7hVyUzb34L4Dio',
    appId: '1:1059073654273:web:cc96cf8d9feb8aa8d64a00',
    messagingSenderId: '1059073654273',
    projectId: 'novelai-61453',
    authDomain: 'novelai-61453.firebaseapp.com',
    storageBucket: 'novelai-61453.firebasestorage.app',
  );
}
